export default [
    'Afghanistan',
    "Armenia",
    `Azerbaijan`,
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'East Timor',
    'Georgia',
    'Hong Kong',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Nepal',
    'Myanmar',
    'Singapore',
    'Pakistan',
    'Saudi Arabia',
    'South Korea',
    'Sri Lanka',
    'Vietnam',
    'United Arab Emirates'
];